[2023-11-05T13:29:34.241+0000] {processor.py:157} INFO - Started process (PID=7562) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:34.244+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:29:34.247+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:29:34.247+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:34.257+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:29:34.254+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 15
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:29:34.258+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:34.297+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.061 seconds
[2023-11-05T13:29:40.289+0000] {processor.py:157} INFO - Started process (PID=7567) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:40.291+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:29:40.293+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:29:40.292+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:40.302+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:29:40.300+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 16
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:29:40.303+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:40.340+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.058 seconds
[2023-11-05T13:29:42.361+0000] {processor.py:157} INFO - Started process (PID=7572) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:42.364+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:29:42.367+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:29:42.366+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:42.387+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:29:42.384+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 16
    )
    ^
SyntaxError: invalid syntax
[2023-11-05T13:29:42.389+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:42.432+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.108 seconds
[2023-11-05T13:29:44.531+0000] {processor.py:157} INFO - Started process (PID=7582) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:44.539+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:29:44.542+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:29:44.541+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:44.685+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:29:44.683+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 16
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:29:44.691+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:44.830+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.310 seconds
[2023-11-05T13:29:46.737+0000] {processor.py:157} INFO - Started process (PID=7587) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:46.739+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:29:46.741+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:29:46.741+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:46.750+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:29:46.748+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 16
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:29:46.751+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:46.791+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.060 seconds
[2023-11-05T13:29:48.948+0000] {processor.py:157} INFO - Started process (PID=7592) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:48.960+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:29:48.975+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:29:48.974+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:49.080+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:29:49.077+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:29:49.106+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:49.200+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.264 seconds
[2023-11-05T13:29:51.026+0000] {processor.py:157} INFO - Started process (PID=7597) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:51.028+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:29:51.031+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:29:51.030+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:51.049+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:29:51.046+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:29:51.052+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:51.102+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.084 seconds
[2023-11-05T13:29:53.041+0000] {processor.py:157} INFO - Started process (PID=7602) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:53.043+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:29:53.044+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:29:53.044+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:53.053+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:29:53.051+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 17
    )
    ^
SyntaxError: invalid syntax
[2023-11-05T13:29:53.054+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:53.089+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.053 seconds
[2023-11-05T13:29:55.095+0000] {processor.py:157} INFO - Started process (PID=7607) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:55.098+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:29:55.101+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:29:55.100+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:55.131+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:29:55.128+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:29:55.136+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:55.172+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.088 seconds
[2023-11-05T13:29:57.199+0000] {processor.py:157} INFO - Started process (PID=7612) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:57.201+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:29:57.203+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:29:57.202+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:57.213+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:29:57.210+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:29:57.214+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:57.256+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.063 seconds
[2023-11-05T13:29:59.242+0000] {processor.py:157} INFO - Started process (PID=7617) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:59.244+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:29:59.249+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:29:59.248+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:59.259+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:29:59.258+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:29:59.261+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:29:59.292+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.058 seconds
[2023-11-05T13:30:03.439+0000] {processor.py:157} INFO - Started process (PID=7634) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:03.441+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:30:03.443+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:03.442+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:03.464+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:03.462+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:30:03.465+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:03.502+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.068 seconds
[2023-11-05T13:30:05.463+0000] {processor.py:157} INFO - Started process (PID=7639) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:05.468+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:30:05.486+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:05.485+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:05.499+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:05.497+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:30:05.501+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:05.542+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.088 seconds
[2023-11-05T13:30:07.588+0000] {processor.py:157} INFO - Started process (PID=7644) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:07.590+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:30:07.593+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:07.592+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:07.602+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:07.600+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 18
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:30:07.603+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:07.645+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.062 seconds
[2023-11-05T13:30:09.640+0000] {processor.py:157} INFO - Started process (PID=7649) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:09.643+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:30:09.645+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:09.645+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:09.660+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:09.657+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 18
    )
    ^
SyntaxError: invalid syntax
[2023-11-05T13:30:09.664+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:09.738+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.105 seconds
[2023-11-05T13:30:11.722+0000] {processor.py:157} INFO - Started process (PID=7654) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:11.724+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:30:11.725+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:11.725+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:11.735+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:11.733+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 18
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:30:11.736+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:11.781+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.066 seconds
[2023-11-05T13:30:15.883+0000] {processor.py:157} INFO - Started process (PID=7664) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:15.886+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:30:15.888+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:15.888+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:15.909+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:15.904+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 18
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:30:15.911+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:15.963+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.089 seconds
[2023-11-05T13:30:17.942+0000] {processor.py:157} INFO - Started process (PID=7669) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:17.944+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:30:17.946+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:17.946+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:17.961+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:17.958+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 18
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:30:17.962+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:18.035+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.101 seconds
[2023-11-05T13:30:22.124+0000] {processor.py:157} INFO - Started process (PID=7674) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:22.126+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:30:22.127+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:22.127+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:22.193+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:22.190+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 18
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:30:22.197+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:22.290+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.172 seconds
[2023-11-05T13:30:26.296+0000] {processor.py:157} INFO - Started process (PID=7679) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:26.298+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:30:26.300+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:26.299+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:26.312+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:26.310+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 18
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:30:26.314+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:26.352+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.064 seconds
[2023-11-05T13:30:28.399+0000] {processor.py:157} INFO - Started process (PID=7684) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:28.400+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:30:28.401+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:28.401+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:28.410+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:28.409+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 19
    def
       ^
SyntaxError: invalid syntax
[2023-11-05T13:30:28.411+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:28.445+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.052 seconds
[2023-11-05T13:30:36.531+0000] {processor.py:157} INFO - Started process (PID=7701) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:36.533+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:30:36.537+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:36.536+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:36.549+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:36.546+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 19
    def example_
               ^
SyntaxError: invalid syntax
[2023-11-05T13:30:36.550+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:36.586+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.062 seconds
[2023-11-05T13:30:40.572+0000] {processor.py:157} INFO - Started process (PID=7706) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:40.574+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:30:40.577+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:40.576+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:40.587+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:40.585+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 19
    def example_taskflow
                       ^
SyntaxError: invalid syntax
[2023-11-05T13:30:40.589+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:40.647+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.082 seconds
[2023-11-05T13:30:42.670+0000] {processor.py:157} INFO - Started process (PID=7711) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:42.672+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:30:42.674+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:42.673+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:42.686+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:42.683+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 19
    def example_taskflow_dag
                           ^
SyntaxError: invalid syntax
[2023-11-05T13:30:42.687+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:42.729+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.066 seconds
[2023-11-05T13:30:44.817+0000] {processor.py:157} INFO - Started process (PID=7721) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:44.819+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:30:44.821+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:44.821+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:44.830+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:44.829+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 19
    def example_taskflow_dag()
                             ^
SyntaxError: invalid syntax
[2023-11-05T13:30:44.831+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:44.864+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.053 seconds
[2023-11-05T13:30:46.836+0000] {processor.py:157} INFO - Started process (PID=7726) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:46.838+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:30:46.840+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:46.839+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:46.851+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:46.846+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 20
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:30:46.853+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:46.908+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.077 seconds
[2023-11-05T13:30:50.994+0000] {processor.py:157} INFO - Started process (PID=7731) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:51.007+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:30:51.017+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:51.016+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:51.032+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:51.030+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 22
    @task
        ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:30:51.034+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:51.065+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.083 seconds
[2023-11-05T13:30:53.015+0000] {processor.py:157} INFO - Started process (PID=7736) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:53.017+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:30:53.019+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:53.018+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:53.026+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:53.024+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 23
    def
       ^
SyntaxError: invalid syntax
[2023-11-05T13:30:53.026+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:53.068+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.057 seconds
[2023-11-05T13:30:55.039+0000] {processor.py:157} INFO - Started process (PID=7741) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:55.041+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:30:55.044+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:55.043+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:55.054+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:55.052+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 23
    def get
          ^
SyntaxError: invalid syntax
[2023-11-05T13:30:55.055+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:55.090+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.057 seconds
[2023-11-05T13:30:57.063+0000] {processor.py:157} INFO - Started process (PID=7746) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:57.065+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:30:57.070+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:57.070+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:57.083+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:30:57.080+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 23
    def get_name
               ^
SyntaxError: invalid syntax
[2023-11-05T13:30:57.084+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:30:57.147+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.092 seconds
[2023-11-05T13:31:02.183+0000] {processor.py:157} INFO - Started process (PID=7751) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:02.185+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:31:02.187+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:31:02.186+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:02.196+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:31:02.194+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 24
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:31:02.197+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:02.228+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.052 seconds
[2023-11-05T13:31:04.428+0000] {processor.py:157} INFO - Started process (PID=7768) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:04.431+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:31:04.435+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:31:04.434+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:04.450+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:31:04.447+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 23
    def get_name():
                  ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:31:04.451+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:04.487+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.070 seconds
[2023-11-05T13:31:06.436+0000] {processor.py:157} INFO - Started process (PID=7773) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:06.438+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:31:06.440+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:31:06.440+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:06.449+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:31:06.448+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 23
    def get_name():
                  ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:31:06.451+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:06.484+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.056 seconds
[2023-11-05T13:31:12.482+0000] {processor.py:157} INFO - Started process (PID=7778) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:12.484+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:31:12.486+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:31:12.486+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:12.497+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:31:12.494+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 23
    def get_name():
                  ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:31:12.498+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:12.535+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.059 seconds
[2023-11-05T13:31:14.591+0000] {processor.py:157} INFO - Started process (PID=7783) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:14.594+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:31:14.597+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:31:14.596+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:14.606+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:31:14.604+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 23
    def get_name():
                  ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:31:14.606+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:14.646+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.062 seconds
[2023-11-05T13:31:16.719+0000] {processor.py:157} INFO - Started process (PID=7793) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:16.721+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:31:16.723+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:31:16.722+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:16.731+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:31:16.730+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 23
    def get_name():
                  ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:31:16.733+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:16.769+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.056 seconds
[2023-11-05T13:31:20.757+0000] {processor.py:157} INFO - Started process (PID=7798) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:20.758+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:31:20.760+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:31:20.759+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:20.769+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:31:20.767+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 23
    def get_name():
                  ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:31:20.771+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:20.830+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.080 seconds
[2023-11-05T13:31:22.855+0000] {processor.py:157} INFO - Started process (PID=7803) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:22.858+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:31:22.861+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:31:22.860+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:22.878+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:31:22.875+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 24
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:31:22.880+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:22.918+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.071 seconds
[2023-11-05T13:31:25.050+0000] {processor.py:157} INFO - Started process (PID=7808) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:25.053+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:31:25.056+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:31:25.055+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:25.069+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:25.097+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.057 seconds
[2023-11-05T13:31:27.093+0000] {processor.py:157} INFO - Started process (PID=7813) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:27.095+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:31:27.097+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:31:27.097+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:27.110+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:27.139+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.051 seconds
[2023-11-05T13:31:40.286+0000] {processor.py:157} INFO - Started process (PID=7830) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:40.292+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:31:40.295+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:31:40.294+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:40.341+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:31:40.338+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 27
    }
    ^
SyntaxError: invalid syntax
[2023-11-05T13:31:40.344+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:40.421+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.144 seconds
[2023-11-05T13:31:46.500+0000] {processor.py:157} INFO - Started process (PID=7840) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:46.502+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:31:46.503+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:31:46.503+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:46.511+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:46.540+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.046 seconds
[2023-11-05T13:31:50.548+0000] {processor.py:157} INFO - Started process (PID=7845) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:50.550+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:31:50.554+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:31:50.553+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:50.570+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:50.606+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.067 seconds
[2023-11-05T13:31:54.636+0000] {processor.py:157} INFO - Started process (PID=7850) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:54.637+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:31:54.640+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:31:54.640+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:54.673+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:54.715+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.086 seconds
[2023-11-05T13:31:58.737+0000] {processor.py:157} INFO - Started process (PID=7855) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:58.739+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:31:58.742+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:31:58.742+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:58.762+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:31:58.791+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.064 seconds
[2023-11-05T13:32:04.943+0000] {processor.py:157} INFO - Started process (PID=7867) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:04.948+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:32:04.968+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:32:04.967+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:04.996+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:05.092+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.159 seconds
[2023-11-05T13:32:07.202+0000] {processor.py:157} INFO - Started process (PID=7877) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:07.204+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:32:07.207+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:32:07.206+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:07.218+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:32:07.217+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 28
    @
    ^
SyntaxError: invalid syntax
[2023-11-05T13:32:07.220+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:07.273+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.078 seconds
[2023-11-05T13:32:10.241+0000] {processor.py:157} INFO - Started process (PID=7882) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:10.243+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:32:10.246+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:32:10.245+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:10.259+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:32:10.257+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 29
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:32:10.260+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:10.345+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.111 seconds
[2023-11-05T13:32:14.402+0000] {processor.py:157} INFO - Started process (PID=7887) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:14.405+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:32:14.408+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:32:14.408+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:14.424+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:32:14.420+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 29
    def get_age
              ^
SyntaxError: invalid syntax
[2023-11-05T13:32:14.426+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:14.475+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.083 seconds
[2023-11-05T13:32:16.491+0000] {processor.py:157} INFO - Started process (PID=7892) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:16.493+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:32:16.495+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:32:16.495+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:16.506+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:32:16.503+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 29
    def get_age()
                ^
SyntaxError: invalid syntax
[2023-11-05T13:32:16.507+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:16.546+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.060 seconds
[2023-11-05T13:32:18.650+0000] {processor.py:157} INFO - Started process (PID=7902) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:18.652+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:32:18.655+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:32:18.654+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:18.665+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:32:18.663+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 30
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:32:18.667+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:18.702+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.058 seconds
[2023-11-05T13:32:20.671+0000] {processor.py:157} INFO - Started process (PID=7907) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:20.673+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:32:20.675+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:32:20.675+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:20.691+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:20.721+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.055 seconds
[2023-11-05T13:32:36.923+0000] {processor.py:157} INFO - Started process (PID=7924) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:36.925+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:32:36.927+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:32:36.926+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:36.938+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:37.012+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.096 seconds
[2023-11-05T13:32:38.951+0000] {processor.py:157} INFO - Started process (PID=7929) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:38.953+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:32:38.954+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:32:38.954+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:38.966+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:38.994+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.049 seconds
[2023-11-05T13:32:47.020+0000] {processor.py:157} INFO - Started process (PID=7934) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:47.027+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:32:47.033+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:32:47.033+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:47.045+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:32:47.043+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 33
    def greetings()
                  ^
SyntaxError: invalid syntax
[2023-11-05T13:32:47.046+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:47.086+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.073 seconds
[2023-11-05T13:32:51.193+0000] {processor.py:157} INFO - Started process (PID=7944) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:51.195+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:32:51.197+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:32:51.196+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:51.208+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:32:51.206+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 33
    def greetings(firstname)
                           ^
SyntaxError: invalid syntax
[2023-11-05T13:32:51.209+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:51.250+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.095 seconds
[2023-11-05T13:32:55.288+0000] {processor.py:157} INFO - Started process (PID=7949) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:55.290+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:32:55.292+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:32:55.292+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:55.302+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:32:55.300+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 33
    def greetings(firstname, last)
                                 ^
SyntaxError: invalid syntax
[2023-11-05T13:32:55.303+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:55.333+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.050 seconds
[2023-11-05T13:32:59.392+0000] {processor.py:157} INFO - Started process (PID=7954) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:59.394+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:32:59.396+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:32:59.395+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:59.406+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:32:59.404+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 33
    def greetings(firstname, last_name)
                                      ^
SyntaxError: invalid syntax
[2023-11-05T13:32:59.407+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:32:59.447+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.060 seconds
[2023-11-05T13:33:01.431+0000] {processor.py:157} INFO - Started process (PID=7959) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:01.433+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:33:01.435+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:33:01.434+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:01.445+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:33:01.442+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 34
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-05T13:33:01.446+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:01.479+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.053 seconds
[2023-11-05T13:33:05.549+0000] {processor.py:157} INFO - Started process (PID=7971) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:05.551+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:33:05.553+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:33:05.552+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:05.564+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:05.591+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.047 seconds
[2023-11-05T13:33:07.647+0000] {processor.py:157} INFO - Started process (PID=7981) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:07.648+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:33:07.650+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:33:07.650+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:07.662+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:07.690+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.049 seconds
[2023-11-05T13:33:09.678+0000] {processor.py:157} INFO - Started process (PID=7986) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:09.680+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:33:09.682+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:33:09.681+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:09.694+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:09.723+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.052 seconds
[2023-11-05T13:33:15.892+0000] {processor.py:157} INFO - Started process (PID=7991) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:15.901+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:33:15.920+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:33:15.919+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:15.965+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:16.010+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.127 seconds
[2023-11-05T13:33:16.971+0000] {processor.py:157} INFO - Started process (PID=7996) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:16.973+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:33:16.975+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:33:16.975+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:16.989+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:33:16.987+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 34
    print(f"Hello, My name is {}")
          ^
SyntaxError: f-string: empty expression not allowed
[2023-11-05T13:33:16.990+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:17.028+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.065 seconds
[2023-11-05T13:33:19.184+0000] {processor.py:157} INFO - Started process (PID=8006) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:19.188+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:33:19.190+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:33:19.189+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:19.202+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:19.239+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.060 seconds
[2023-11-05T13:33:21.213+0000] {processor.py:157} INFO - Started process (PID=8011) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:21.215+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:33:21.218+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:33:21.217+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:21.229+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:33:21.227+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 34
    print(f"Hello, My name is {firstname} {}")
          ^
SyntaxError: f-string: empty expression not allowed
[2023-11-05T13:33:21.230+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:21.274+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.066 seconds
[2023-11-05T13:33:23.320+0000] {processor.py:157} INFO - Started process (PID=8016) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:23.322+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:33:23.323+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:33:23.323+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:23.334+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:23.363+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.048 seconds
[2023-11-05T13:33:29.375+0000] {processor.py:157} INFO - Started process (PID=8021) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:29.377+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:33:29.379+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:33:29.379+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:29.391+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:33:29.389+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 34
    print(f"Hello, My name is {firstname} {last_name} and I'm {}")
          ^
SyntaxError: f-string: empty expression not allowed
[2023-11-05T13:33:29.392+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:29.430+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.062 seconds
[2023-11-05T13:33:31.501+0000] {processor.py:157} INFO - Started process (PID=8026) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:31.509+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:33:31.512+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:33:31.511+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:31.529+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:31.571+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.077 seconds
[2023-11-05T13:33:37.561+0000] {processor.py:157} INFO - Started process (PID=8038) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:37.563+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:33:37.564+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:33:37.564+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:37.578+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:37.630+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.075 seconds
[2023-11-05T13:33:39.690+0000] {processor.py:157} INFO - Started process (PID=8048) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:39.691+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:33:39.693+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:33:39.693+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:39.705+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:39.735+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.051 seconds
[2023-11-05T13:33:43.720+0000] {processor.py:157} INFO - Started process (PID=8053) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:43.722+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:33:43.724+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:33:43.724+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:43.739+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:43.769+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.055 seconds
[2023-11-05T13:33:47.832+0000] {processor.py:157} INFO - Started process (PID=8058) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:47.834+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:33:47.835+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:33:47.835+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:47.847+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:33:47.875+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.049 seconds
[2023-11-05T13:34:16.237+0000] {processor.py:157} INFO - Started process (PID=8080) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:34:16.245+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:34:16.247+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:34:16.246+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:34:16.259+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:34:16.286+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.055 seconds
[2023-11-05T13:34:18.291+0000] {processor.py:157} INFO - Started process (PID=8085) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:34:18.295+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:34:18.301+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:34:18.300+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:34:18.321+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:34:18.319+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 36
    name_dict =
               ^
SyntaxError: invalid syntax
[2023-11-05T13:34:18.322+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:34:18.359+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.075 seconds
[2023-11-05T13:34:22.442+0000] {processor.py:157} INFO - Started process (PID=8095) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:34:22.444+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:34:22.447+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:34:22.446+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:34:22.456+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:34:22.483+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.051 seconds
[2023-11-05T13:34:34.703+0000] {processor.py:157} INFO - Started process (PID=8107) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:34:34.706+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:34:34.714+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:34:34.713+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:34:34.783+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:34:34.875+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.182 seconds
[2023-11-05T13:34:36.723+0000] {processor.py:157} INFO - Started process (PID=8112) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:34:36.725+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:34:36.728+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:34:36.727+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:34:36.740+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:34:36.805+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.087 seconds
[2023-11-05T13:34:38.747+0000] {processor.py:157} INFO - Started process (PID=8117) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:34:38.749+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:34:38.751+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:34:38.751+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:34:38.769+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:34:38.800+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.060 seconds
[2023-11-05T13:34:46.893+0000] {processor.py:157} INFO - Started process (PID=8127) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:34:46.894+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:34:46.896+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:34:46.896+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:34:46.907+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:34:46.934+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.047 seconds
[2023-11-05T13:34:53.013+0000] {processor.py:157} INFO - Started process (PID=8137) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:34:53.015+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:34:53.016+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:34:53.016+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:34:53.026+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:34:53.024+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 35
    l    age = get_age()
         ^
SyntaxError: invalid syntax
[2023-11-05T13:34:53.027+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:34:53.064+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.057 seconds
[2023-11-05T13:34:55.032+0000] {processor.py:157} INFO - Started process (PID=8142) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:34:55.034+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:34:55.036+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:34:55.036+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:34:55.048+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:34:55.077+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.052 seconds
[2023-11-05T13:35:25.420+0000] {processor.py:157} INFO - Started process (PID=8164) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:35:25.422+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:35:25.424+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:35:25.424+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:35:25.434+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:35:25.462+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.047 seconds
[2023-11-05T13:35:55.834+0000] {processor.py:157} INFO - Started process (PID=8186) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:35:55.836+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:35:55.839+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:35:55.838+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:35:55.848+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:35:55.872+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.044 seconds
[2023-11-05T13:36:26.112+0000] {processor.py:157} INFO - Started process (PID=8208) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:36:26.119+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:36:26.121+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:36:26.121+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:36:26.128+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:36:26.151+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.044 seconds
[2023-11-05T13:36:56.489+0000] {processor.py:157} INFO - Started process (PID=8230) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:36:56.490+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:36:56.492+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:36:56.492+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:36:56.499+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:36:56.521+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.038 seconds
[2023-11-05T13:37:26.895+0000] {processor.py:157} INFO - Started process (PID=8252) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:37:26.901+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:37:26.903+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:37:26.902+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:37:26.910+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:37:26.933+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.043 seconds
[2023-11-05T13:37:38.019+0000] {processor.py:157} INFO - Started process (PID=8264) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:37:38.021+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:37:38.023+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:37:38.022+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:37:38.035+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:37:38.059+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.046 seconds
[2023-11-05T13:37:49.161+0000] {processor.py:157} INFO - Started process (PID=8274) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:37:49.163+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:37:49.165+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:37:49.164+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:37:49.175+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:37:49.199+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.043 seconds
[2023-11-05T13:38:03.324+0000] {processor.py:157} INFO - Started process (PID=8284) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:38:03.326+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:38:03.328+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:38:03.327+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:38:03.338+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:38:03.366+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.048 seconds
[2023-11-05T13:38:07.363+0000] {processor.py:157} INFO - Started process (PID=8296) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:38:07.371+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:38:07.373+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:38:07.373+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:38:07.386+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:38:07.412+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.056 seconds
[2023-11-05T13:38:15.500+0000] {processor.py:157} INFO - Started process (PID=8306) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:38:15.502+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:38:15.503+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:38:15.503+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:38:15.514+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:38:15.542+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.049 seconds
[2023-11-05T13:38:17.517+0000] {processor.py:157} INFO - Started process (PID=8311) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:38:17.519+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:38:17.521+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:38:17.521+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:38:17.533+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:38:17.558+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.046 seconds
[2023-11-05T13:38:22.565+0000] {processor.py:157} INFO - Started process (PID=8316) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:38:22.572+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:38:22.574+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:38:22.574+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:38:22.587+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:38:22.624+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.066 seconds
[2023-11-05T13:38:34.757+0000] {processor.py:157} INFO - Started process (PID=8333) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:38:34.760+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:38:34.764+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:38:34.763+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:38:34.782+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:38:34.835+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.084 seconds
[2023-11-05T13:38:56.957+0000] {processor.py:157} INFO - Started process (PID=8348) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:38:56.965+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:38:56.968+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:38:56.967+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:38:56.985+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:38:56.983+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 38
    greetings(first_name=)
                         ^
SyntaxError: invalid syntax
[2023-11-05T13:38:56.987+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:38:57.035+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.109 seconds
[2023-11-05T13:39:01.023+0000] {processor.py:157} INFO - Started process (PID=8353) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:01.026+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:39:01.030+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:39:01.029+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:01.045+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:01.081+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.068 seconds
[2023-11-05T13:39:03.112+0000] {processor.py:157} INFO - Started process (PID=8358) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:03.114+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:39:03.117+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:39:03.116+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:03.137+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:03.176+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.071 seconds
[2023-11-05T13:39:05.180+0000] {processor.py:157} INFO - Started process (PID=8370) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:05.182+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:39:05.184+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:39:05.183+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:05.198+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:05.232+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.057 seconds
[2023-11-05T13:39:07.259+0000] {processor.py:157} INFO - Started process (PID=8375) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:07.261+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:39:07.264+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:39:07.263+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:07.277+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:07.308+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.055 seconds
[2023-11-05T13:39:09.328+0000] {processor.py:157} INFO - Started process (PID=8380) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:09.330+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:39:09.331+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:39:09.331+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:09.343+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:09.370+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.048 seconds
[2023-11-05T13:39:11.420+0000] {processor.py:157} INFO - Started process (PID=8385) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:11.422+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:39:11.425+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:39:11.424+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:11.442+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:11.473+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.063 seconds
[2023-11-05T13:39:13.534+0000] {processor.py:157} INFO - Started process (PID=8395) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:13.536+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:39:13.539+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:39:13.538+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:13.551+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:13.599+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.070 seconds
[2023-11-05T13:39:15.553+0000] {processor.py:157} INFO - Started process (PID=8400) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:15.555+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:39:15.557+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:39:15.557+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:15.569+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:15.601+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.054 seconds
[2023-11-05T13:39:17.573+0000] {processor.py:157} INFO - Started process (PID=8405) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:17.575+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:39:17.577+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:39:17.577+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:17.589+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:17.617+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.050 seconds
[2023-11-05T13:39:19.597+0000] {processor.py:157} INFO - Started process (PID=8410) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:19.599+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:39:19.601+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:39:19.600+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:19.612+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:19.640+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.048 seconds
[2023-11-05T13:39:21.621+0000] {processor.py:157} INFO - Started process (PID=8415) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:21.623+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:39:21.625+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:39:21.624+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:21.639+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:21.785+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.170 seconds
[2023-11-05T13:39:25.910+0000] {processor.py:157} INFO - Started process (PID=8425) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:25.912+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:39:25.914+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:39:25.913+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:25.933+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:39:25.931+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 40
    last_na
    ^
SyntaxError: positional argument follows keyword argument
[2023-11-05T13:39:25.935+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:25.981+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.078 seconds
[2023-11-05T13:39:27.952+0000] {processor.py:157} INFO - Started process (PID=8430) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:27.954+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:39:27.956+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:39:27.955+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:27.976+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:39:27.974+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 41
    )
    ^
SyntaxError: invalid syntax
[2023-11-05T13:39:27.978+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:28.042+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.097 seconds
[2023-11-05T13:39:30.070+0000] {processor.py:157} INFO - Started process (PID=8435) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:30.072+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:39:30.074+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:39:30.074+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:30.085+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:30.122+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.058 seconds
[2023-11-05T13:39:32.123+0000] {processor.py:157} INFO - Started process (PID=8440) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:32.124+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:39:32.126+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:39:32.126+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:32.139+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:32.170+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.054 seconds
[2023-11-05T13:39:35.183+0000] {processor.py:157} INFO - Started process (PID=8452) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:35.185+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:39:35.187+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:39:35.186+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:35.199+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:35.270+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.093 seconds
[2023-11-05T13:39:41.397+0000] {processor.py:157} INFO - Started process (PID=8457) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:41.399+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:39:41.401+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:39:41.400+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:41.414+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:41.442+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.051 seconds
[2023-11-05T13:39:43.499+0000] {processor.py:157} INFO - Started process (PID=8462) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:43.501+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:39:43.504+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:39:43.503+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:43.518+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:43.551+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.062 seconds
[2023-11-05T13:39:45.613+0000] {processor.py:157} INFO - Started process (PID=8472) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:45.617+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:39:45.620+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:39:45.619+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:45.640+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:45.698+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.091 seconds
[2023-11-05T13:39:47.744+0000] {processor.py:157} INFO - Started process (PID=8477) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:47.746+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:39:47.748+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:39:47.747+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:47.758+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:47.783+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.044 seconds
[2023-11-05T13:39:51.816+0000] {processor.py:157} INFO - Started process (PID=8482) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:51.828+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:39:51.831+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:39:51.831+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:51.849+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:39:51.846+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 44, in <module>
    greet
NameError: name 'greet' is not defined
[2023-11-05T13:39:51.850+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:51.913+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.107 seconds
[2023-11-05T13:39:53.886+0000] {processor.py:157} INFO - Started process (PID=8487) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:53.888+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:39:53.890+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:39:53.889+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:53.901+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:39:53.899+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 44
    greet_lag =
               ^
SyntaxError: invalid syntax
[2023-11-05T13:39:53.903+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:53.940+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.060 seconds
[2023-11-05T13:39:58.023+0000] {processor.py:157} INFO - Started process (PID=8497) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:58.025+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:39:58.028+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:39:58.028+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:58.041+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:39:58.094+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.076 seconds
[2023-11-05T13:40:00.123+0000] {processor.py:157} INFO - Started process (PID=8502) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:40:00.124+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:40:00.127+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:40:00.126+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:40:00.169+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:40:00.163+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 44, in <module>
    greet_lag = example_taskflow_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3843, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/taskflow_api_dag.py", line 38, in example_taskflow_dag
    greetings(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 346, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 208, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 2952, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'firstname'
[2023-11-05T13:40:00.170+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:40:00.199+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.082 seconds
[2023-11-05T13:40:04.171+0000] {processor.py:157} INFO - Started process (PID=8507) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:40:04.173+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:40:04.175+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:40:04.174+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:40:04.209+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:40:04.199+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 45, in <module>
    greet_lag = example_taskflow_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3843, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/taskflow_api_dag.py", line 38, in example_taskflow_dag
    greetings(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 346, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 208, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 2952, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'firstname'
[2023-11-05T13:40:04.211+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:40:04.257+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.091 seconds
[2023-11-05T13:40:08.312+0000] {processor.py:157} INFO - Started process (PID=8519) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:40:08.314+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:40:08.318+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:40:08.317+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:40:08.352+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:40:08.344+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 45, in <module>
    greet_lag = example_taskflow_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3843, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/taskflow_api_dag.py", line 38, in example_taskflow_dag
    greetings(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 346, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 208, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 2952, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'firstname'
[2023-11-05T13:40:08.353+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:40:08.392+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.086 seconds
[2023-11-05T13:40:18.503+0000] {processor.py:157} INFO - Started process (PID=8529) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:40:18.505+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:40:18.507+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:40:18.506+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:40:18.554+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:40:18.546+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 45, in <module>
    greet_lag = example_taskflow_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3843, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/taskflow_api_dag.py", line 38, in example_taskflow_dag
    greetings(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 346, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 208, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 2952, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'firstname'
[2023-11-05T13:40:18.556+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:40:18.605+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.110 seconds
[2023-11-05T13:40:20.638+0000] {processor.py:157} INFO - Started process (PID=8534) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:40:20.639+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:40:20.643+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:40:20.642+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:40:20.676+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:40:20.668+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 45, in <module>
    greet_lag = example_taskflow_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3843, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/taskflow_api_dag.py", line 38, in example_taskflow_dag
    greetings(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 346, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 208, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 2952, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'firstname'
[2023-11-05T13:40:20.677+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:40:20.712+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.079 seconds
[2023-11-05T13:40:22.684+0000] {processor.py:157} INFO - Started process (PID=8539) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:40:22.686+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:40:22.688+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:40:22.687+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:40:22.727+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:40:22.720+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 45, in <module>
    greet_lag = example_taskflow_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3843, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/taskflow_api_dag.py", line 38, in example_taskflow_dag
    greetings(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 346, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 208, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 2952, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'firstname'
[2023-11-05T13:40:22.728+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:40:22.761+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.083 seconds
[2023-11-05T13:40:24.787+0000] {processor.py:157} INFO - Started process (PID=8544) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:40:24.793+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:40:24.796+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:40:24.795+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:40:24.844+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:40:24.836+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 45, in <module>
    greet_lag = example_taskflow_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3843, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/taskflow_api_dag.py", line 38, in example_taskflow_dag
    greetings(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 346, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 208, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 2952, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'firstname'
[2023-11-05T13:40:24.845+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:40:24.878+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.100 seconds
[2023-11-05T13:40:26.945+0000] {processor.py:157} INFO - Started process (PID=8554) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:40:26.947+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:40:26.949+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:40:26.948+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:40:26.990+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:40:26.984+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 45, in <module>
    greet_lag = example_taskflow_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3843, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/taskflow_api_dag.py", line 38, in example_taskflow_dag
    greetings(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 346, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 208, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 2952, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'firstname'
[2023-11-05T13:40:26.993+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:40:27.030+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.092 seconds
[2023-11-05T13:40:57.382+0000] {processor.py:157} INFO - Started process (PID=8576) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:40:57.385+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:40:57.388+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:40:57.387+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:40:57.421+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:40:57.414+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 45, in <module>
    greet_lag = example_taskflow_dag()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 3843, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/taskflow_api_dag.py", line 38, in example_taskflow_dag
    greetings(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 346, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/python.py", line 49, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 208, in __init__
    inspect.signature(python_callable).bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 2952, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'firstname'
[2023-11-05T13:40:57.422+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:40:57.466+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.092 seconds
[2023-11-05T13:41:08.479+0000] {processor.py:157} INFO - Started process (PID=8588) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:41:08.481+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:41:08.482+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:41:08.482+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:41:08.517+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:41:08.746+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:41:08.745+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-11-05T13:41:08.768+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:41:08.767+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-11-05T13:41:08.784+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:41:08.784+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-11-05T13:41:08.785+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:41:08.785+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:41:08.814+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:41:08.813+0000] {dag.py:2963} INFO - Creating ORM DAG for taskflow_api_dag
[2023-11-05T13:41:08.832+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:41:08.832+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-04T00:00:00+00:00, run_after=2023-11-05T00:00:00+00:00
[2023-11-05T13:41:08.862+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.390 seconds
[2023-11-05T13:41:16.632+0000] {processor.py:157} INFO - Started process (PID=8598) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:41:16.634+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:41:16.635+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:41:16.635+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:41:16.670+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:41:16.690+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:41:16.689+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:41:16.729+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:41:16.729+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-04T00:00:00+00:00, run_after=2023-11-05T00:00:00+00:00
[2023-11-05T13:41:16.771+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.145 seconds
[2023-11-05T13:41:47.021+0000] {processor.py:157} INFO - Started process (PID=8626) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:41:47.022+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:41:47.024+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:41:47.024+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:41:47.047+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:41:47.089+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:41:47.088+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:41:47.124+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:41:47.124+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-05T00:00:00+00:00, run_after=2023-11-06T00:00:00+00:00
[2023-11-05T13:41:47.156+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.141 seconds
[2023-11-05T13:42:17.506+0000] {processor.py:157} INFO - Started process (PID=8648) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:42:17.508+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:42:17.510+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:42:17.509+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:42:17.533+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:42:17.572+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:42:17.572+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:42:17.607+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:42:17.607+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-05T00:00:00+00:00, run_after=2023-11-06T00:00:00+00:00
[2023-11-05T13:42:17.640+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.139 seconds
[2023-11-05T13:42:47.893+0000] {processor.py:157} INFO - Started process (PID=8670) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:42:47.894+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:42:47.896+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:42:47.896+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:42:47.919+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:42:47.959+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:42:47.959+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:42:47.995+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:42:47.994+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-05T00:00:00+00:00, run_after=2023-11-06T00:00:00+00:00
[2023-11-05T13:42:48.028+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.141 seconds
[2023-11-05T13:43:18.377+0000] {processor.py:157} INFO - Started process (PID=8692) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:43:18.378+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:43:18.380+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:43:18.379+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:43:18.403+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:43:18.442+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:43:18.442+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:43:18.478+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:43:18.478+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-05T00:00:00+00:00, run_after=2023-11-06T00:00:00+00:00
[2023-11-05T13:43:18.511+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.140 seconds
[2023-11-05T13:43:48.767+0000] {processor.py:157} INFO - Started process (PID=8714) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:43:48.769+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:43:48.770+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:43:48.770+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:43:48.793+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:43:48.834+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:43:48.834+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:43:48.871+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:43:48.871+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-05T00:00:00+00:00, run_after=2023-11-06T00:00:00+00:00
[2023-11-05T13:43:48.903+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.141 seconds
[2023-11-05T13:44:19.239+0000] {processor.py:157} INFO - Started process (PID=8736) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:44:19.241+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:44:19.243+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:44:19.242+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:44:19.265+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:44:19.305+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:44:19.305+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:44:19.342+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:44:19.341+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-05T00:00:00+00:00, run_after=2023-11-06T00:00:00+00:00
[2023-11-05T13:44:19.374+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.140 seconds
[2023-11-05T13:44:49.651+0000] {processor.py:157} INFO - Started process (PID=8758) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:44:49.653+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:44:49.655+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:44:49.654+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:44:49.678+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:44:49.717+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:44:49.717+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:44:49.752+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:44:49.752+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-05T00:00:00+00:00, run_after=2023-11-06T00:00:00+00:00
[2023-11-05T13:44:49.784+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.138 seconds
[2023-11-05T13:45:20.123+0000] {processor.py:157} INFO - Started process (PID=8780) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:45:20.125+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:45:20.127+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:45:20.127+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:45:20.150+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:45:20.190+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:45:20.190+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:45:20.226+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:45:20.226+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-05T00:00:00+00:00, run_after=2023-11-06T00:00:00+00:00
[2023-11-05T13:45:20.252+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.134 seconds
[2023-11-05T13:45:50.515+0000] {processor.py:157} INFO - Started process (PID=8802) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:45:50.517+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:45:50.519+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:45:50.518+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:45:50.541+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:45:50.581+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:45:50.581+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:45:50.618+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:45:50.618+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-05T00:00:00+00:00, run_after=2023-11-06T00:00:00+00:00
[2023-11-05T13:45:50.652+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.142 seconds
[2023-11-05T13:46:21.002+0000] {processor.py:157} INFO - Started process (PID=8824) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:46:21.003+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:46:21.005+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:46:21.005+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:46:21.028+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:46:21.068+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:46:21.068+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:46:21.105+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:46:21.104+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-05T00:00:00+00:00, run_after=2023-11-06T00:00:00+00:00
[2023-11-05T13:46:21.137+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.140 seconds
[2023-11-05T13:46:51.304+0000] {processor.py:157} INFO - Started process (PID=8836) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:46:51.311+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:46:51.313+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:46:51.312+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:46:51.336+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:46:51.380+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:46:51.379+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:46:51.417+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:46:51.417+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-05T00:00:00+00:00, run_after=2023-11-06T00:00:00+00:00
[2023-11-05T13:46:51.446+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.147 seconds
[2023-11-05T13:47:21.639+0000] {processor.py:157} INFO - Started process (PID=8848) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:47:21.641+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:47:21.642+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:47:21.642+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:47:21.669+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:47:21.717+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:47:21.717+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:47:21.763+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:47:21.763+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-05T00:00:00+00:00, run_after=2023-11-06T00:00:00+00:00
[2023-11-05T13:47:21.802+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.169 seconds
[2023-11-05T13:47:51.864+0000] {processor.py:157} INFO - Started process (PID=8860) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:47:51.865+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:47:51.867+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:47:51.867+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:47:51.894+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:47:51.939+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:47:51.938+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:47:51.979+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:47:51.978+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-05T00:00:00+00:00, run_after=2023-11-06T00:00:00+00:00
[2023-11-05T13:47:52.010+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.153 seconds
[2023-11-05T13:48:22.231+0000] {processor.py:157} INFO - Started process (PID=8871) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:48:22.233+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:48:22.236+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:48:22.235+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:48:22.273+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:48:22.346+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:48:22.345+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:48:22.397+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:48:22.397+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-05T00:00:00+00:00, run_after=2023-11-06T00:00:00+00:00
[2023-11-05T13:48:22.440+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.217 seconds
[2023-11-05T13:48:52.674+0000] {processor.py:157} INFO - Started process (PID=8883) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:48:52.676+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:48:52.679+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:48:52.678+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:48:52.726+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:48:52.808+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:48:52.807+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:48:52.876+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:48:52.876+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-05T00:00:00+00:00, run_after=2023-11-06T00:00:00+00:00
[2023-11-05T13:48:52.929+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.264 seconds
[2023-11-05T13:49:23.173+0000] {processor.py:157} INFO - Started process (PID=8895) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:49:23.180+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:49:23.182+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:49:23.182+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:49:23.209+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:49:23.378+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:49:23.378+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:49:25.247+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:49:25.247+0000] {dag.py:2963} INFO - Creating ORM DAG for taskflow_api_dag
[2023-11-05T13:49:25.271+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:49:25.271+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-04T00:00:00+00:00, run_after=2023-11-05T00:00:00+00:00
[2023-11-05T13:49:25.305+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 2.138 seconds
[2023-11-05T13:49:55.946+0000] {processor.py:157} INFO - Started process (PID=8917) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:49:55.950+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:49:55.951+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:49:55.951+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:49:55.974+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:49:56.014+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:49:56.014+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:49:56.050+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:49:56.049+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-04T00:00:00+00:00, run_after=2023-11-05T00:00:00+00:00
[2023-11-05T13:49:56.076+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.135 seconds
[2023-11-05T13:50:17.277+0000] {processor.py:157} INFO - Started process (PID=8944) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:50:17.279+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:50:17.281+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:50:17.281+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:50:17.293+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:50:17.291+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/taskflow_api_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/taskflow_api_dag.py", line 34
    print(f"
           ^
SyntaxError: EOL while scanning string literal
[2023-11-05T13:50:17.294+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:50:17.332+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.060 seconds
[2023-11-05T13:50:21.408+0000] {processor.py:157} INFO - Started process (PID=8949) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:50:21.409+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:50:21.410+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:50:21.410+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:50:21.442+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:50:21.492+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:50:21.492+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:50:21.530+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:50:21.529+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-04T00:00:00+00:00, run_after=2023-11-05T00:00:00+00:00
[2023-11-05T13:50:21.578+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.175 seconds
[2023-11-05T13:50:27.471+0000] {processor.py:157} INFO - Started process (PID=8954) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:50:27.473+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:50:27.475+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:50:27.474+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:50:27.509+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:50:27.551+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:50:27.550+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:50:27.586+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:50:27.586+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-04T00:00:00+00:00, run_after=2023-11-05T00:00:00+00:00
[2023-11-05T13:50:27.619+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.153 seconds
[2023-11-05T13:50:29.659+0000] {processor.py:157} INFO - Started process (PID=8959) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:50:29.661+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:50:29.663+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:50:29.663+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:50:29.696+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:50:29.736+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:50:29.736+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:50:29.774+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:50:29.774+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-04T00:00:00+00:00, run_after=2023-11-05T00:00:00+00:00
[2023-11-05T13:50:29.822+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.168 seconds
[2023-11-05T13:51:00.081+0000] {processor.py:157} INFO - Started process (PID=8981) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:51:00.083+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:51:00.086+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:51:00.085+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:51:00.111+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:51:00.164+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:51:00.164+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:51:00.225+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:51:00.225+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-04T00:00:00+00:00, run_after=2023-11-05T00:00:00+00:00
[2023-11-05T13:51:00.270+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.194 seconds
[2023-11-05T13:51:30.709+0000] {processor.py:157} INFO - Started process (PID=9003) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:51:30.712+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:51:30.714+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:51:30.713+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:51:30.744+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:51:30.801+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:51:30.801+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:51:30.848+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:51:30.848+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-04T00:00:00+00:00, run_after=2023-11-05T00:00:00+00:00
[2023-11-05T13:51:30.887+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.182 seconds
[2023-11-05T13:52:01.194+0000] {processor.py:157} INFO - Started process (PID=9025) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:52:01.199+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:52:01.203+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:52:01.202+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:52:01.239+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:52:01.297+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:52:01.296+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:52:01.347+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:52:01.346+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-04T00:00:00+00:00, run_after=2023-11-05T00:00:00+00:00
[2023-11-05T13:52:01.385+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.200 seconds
[2023-11-05T13:52:31.790+0000] {processor.py:157} INFO - Started process (PID=9047) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:52:31.797+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:52:31.800+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:52:31.799+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:52:31.834+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:52:31.924+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:52:31.924+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:52:31.980+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:52:31.980+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-04T00:00:00+00:00, run_after=2023-11-05T00:00:00+00:00
[2023-11-05T13:52:32.023+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.240 seconds
[2023-11-05T13:53:02.330+0000] {processor.py:157} INFO - Started process (PID=9069) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:53:02.338+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:53:02.341+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:53:02.340+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:53:02.389+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:53:02.453+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:53:02.452+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:53:02.508+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:53:02.508+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-04T00:00:00+00:00, run_after=2023-11-05T00:00:00+00:00
[2023-11-05T13:53:02.552+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.229 seconds
[2023-11-05T13:53:32.963+0000] {processor.py:157} INFO - Started process (PID=9091) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:53:32.971+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:53:32.975+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:53:32.974+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:53:33.015+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:53:33.079+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:53:33.078+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:53:33.127+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:53:33.126+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-04T00:00:00+00:00, run_after=2023-11-05T00:00:00+00:00
[2023-11-05T13:53:33.169+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.217 seconds
[2023-11-05T13:54:03.490+0000] {processor.py:157} INFO - Started process (PID=9113) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:54:03.492+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:54:03.494+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:54:03.493+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:54:03.535+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:54:03.587+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:54:03.587+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:54:03.636+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:54:03.635+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-04T00:00:00+00:00, run_after=2023-11-05T00:00:00+00:00
[2023-11-05T13:54:03.676+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.193 seconds
[2023-11-05T13:54:34.049+0000] {processor.py:157} INFO - Started process (PID=9135) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:54:34.057+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:54:34.059+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:54:34.059+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:54:34.088+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:54:34.135+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:54:34.134+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:54:34.183+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:54:34.182+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-04T00:00:00+00:00, run_after=2023-11-05T00:00:00+00:00
[2023-11-05T13:54:34.221+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.178 seconds
[2023-11-05T13:55:04.576+0000] {processor.py:157} INFO - Started process (PID=9157) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:55:04.584+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:55:04.586+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:55:04.586+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:55:04.619+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:55:04.676+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:55:04.676+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:55:04.727+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:55:04.727+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-04T00:00:00+00:00, run_after=2023-11-05T00:00:00+00:00
[2023-11-05T13:55:04.772+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.204 seconds
[2023-11-05T13:55:35.094+0000] {processor.py:157} INFO - Started process (PID=9179) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:55:35.102+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:55:35.104+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:55:35.103+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:55:35.127+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:55:35.169+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:55:35.168+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:55:35.204+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:55:35.204+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-04T00:00:00+00:00, run_after=2023-11-05T00:00:00+00:00
[2023-11-05T13:55:35.238+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.149 seconds
[2023-11-05T13:56:05.563+0000] {processor.py:157} INFO - Started process (PID=9201) to work on /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:56:05.565+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/taskflow_api_dag.py for tasks to queue
[2023-11-05T13:56:05.567+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:56:05.567+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:56:05.597+0000] {processor.py:839} INFO - DAG(s) dict_keys(['taskflow_api_dag']) retrieved from /opt/airflow/dags/taskflow_api_dag.py
[2023-11-05T13:56:05.646+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:56:05.646+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-05T13:56:05.690+0000] {logging_mixin.py:151} INFO - [2023-11-05T13:56:05.690+0000] {dag.py:3722} INFO - Setting next_dagrun for taskflow_api_dag to 2023-11-04T00:00:00+00:00, run_after=2023-11-05T00:00:00+00:00
[2023-11-05T13:56:05.725+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/taskflow_api_dag.py took 0.168 seconds
